# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a51e43b79e521189811460de01194e237a419fc22f5cbd6891877d2a7e76051217574ad86a203b4ddf559185c42d3b797a826d23659f0df631560da044887dc4

test:
  secret_key_base: da956a5265dff65f425138d780092444095f53eaa032c6591c7bc6f914294d8dacb66e67891e14af5443518a9514e7280fb387ddb576a297292f71c1aff3e9d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
